name: federation-golang
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "9090:8080"
    command:
      - "/federation-backend"
    volumes:
      - files:/app/files
    restart: always

volumes:
  files:
